[package]
name = "proc_macro_utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
licence.workspace = true

[lib]
proc_macro = true

[dependencies]
inquire = "0.9.1"
quote = "1.0.41"
syn = "2"
